#!/usr/bin/env python3
"""Generate results/r2/RESULTS_R2.md from the stored R2 analysis outputs
(every number is read from a CSV/JSON written by the campaign/analysis
scripts; nothing is typed in by hand)."""
from __future__ import annotations

import json
import math
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
from analyze_r2 import MODES, pivot_table  # noqa: E402

R2 = os.path.join(ROOT, "results", "r2")
TEST = os.path.join(R2, "test")
R1 = os.path.join(ROOT, "results", "campaigns", "main_20261002T092602Z", "aggregate", "scenario_level.csv")


def f(x, nd=3):
    if x is None or (isinstance(x, float) and (math.isnan(x) or math.isinf(x))):
        return "n/a"
    return f"{x:.{nd}f}"


def pfmt(p):
    if p is None or (isinstance(p, float) and math.isnan(p)):
        return "n/a"
    return f"{p:.2e}" if p < 1e-3 else f"{p:.3f}"


def main() -> int:
    desc = pd.read_csv(os.path.join(TEST, "descriptive.csv"))
    conf = pd.read_csv(os.path.join(TEST, "confirmatory.csv"))
    frozen = json.load(open(os.path.join(R2, "frozen_params.json")))
    lock = open(os.path.join(R2, "frozen_params.sha256")).read().split()[0]
    camp = {n: json.load(open(os.path.join(TEST, f"campaign_{n}.json"))) for n in ("main", "sweep")}
    L = []
    L.append("# R2 results: real-detector-trace study (test split)\n")
    L.append("Generated by `scripts/r2/make_report_r2.py` from stored CSV/JSON outputs. Detector predictions, "
             "boxes and mAP are REAL; watcher features are computed from REAL frames; M7 timing, RPC, wake-up and "
             "all power values are SIMULATED (uncalibrated, `config/power_model.json`). Energy is MODELED.\n")
    L.append("## Campaign\n")
    for n, c in camp.items():
        L.append(f"* `{n}`: {c['n_runs']} runs (8 modes x {len(c['scenarios'])} scenario(s) x "
                 f"{len(c['intensities'])} intensity(ies) x 30 seeds x 5 test segments), frozen parameters "
                 f"SHA-256 `{c['frozen_sha256'][:16]}...` committed in `{c['frozen_commit'].split()[0][:7]}`.")
    L.append(f"* Frozen parameter file: `results/r2/frozen_params.json` (SHA-256 `{lock}`), tuned on the "
             "validation split only (`docs/PREREGISTERED_R2_ANALYSIS.md`, amendment 1 included).")
    sp = json.load(open(os.path.join(ROOT, "data", "splits", "r2_kitti_splits.json")))
    segs = [g for g in sp["segments"] if g["split"] == "test"]
    seg = pd.read_csv(os.path.join(TEST, "runs_segments_main.csv.gz"))
    one = seg[(seg["mode"] == "always_on") & (seg.scenario == "clean") & (seg.seed == 1)]
    L.append("* Test split: KITTI tracking static-camera segments " +
             ", ".join(f"{g['sequence']} ({g['first_frame']}-{g['last_frame']})" for g in segs) +
             f": {int(one.frames.sum())} real frames, {int(one.moving_tracks.sum())} moving tracks "
             f"({int(one.burst_tracks.sum())} in bursts).\n")
    L.append("## Confirmatory hypotheses (pre-registered, Holm over C1-C8, C10, C11; C9 non-inferiority)\n")
    L.append("| id | scenario | metric | comparison | mean A | mean B | mean diff [95% CI] | rank-biserial | "
             "non-zero pairs | p (Holm) | verdict |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for r in conf.itertuples():
        nd = 0 if r.metric.startswith("energy") else 3
        L.append(f"| {r.id} | {r.scenario}{' x' + format(r.intensity, 'g') if r.scenario == 'spam' else ''} | "
                 f"{r.metric} | {r.a} vs {r.b} | {f(r.mean_a, nd)} | {f(r.mean_b, nd)} | {f(r.mean_diff, nd)} "
                 f"[{f(r.ci95_diff_low, nd)}, {f(r.ci95_diff_high, nd)}] | {f(r.rank_biserial, 2)} | {r.n_nonzero} | "
                 f"{pfmt(r.p_holm) if r.id != 'C9' else 'n/a (CI rule)'} | **{r.verdict}** |")
    L.append("")
    for sc, it, title in (("clean", 1.0, "Clean (no overlay; seeds differ only in simulated timing; descriptive)"),
                          ("noisy", 1.0, "Noisy camera"), ("mixed", 1.0, "Mixed attack (spam + replay, x1)"),
                          ("replay_exact", 1.0, "Exact replay"), ("replay_perturbed", 1.0, "Perturbed replay"),
                          ("spam", 8.0, "Trigger spam x8")):
        L.append(f"### {title}: mean ± SD over 30 realizations\n")
        L.append(pivot_table(desc, sc, it, ["track_recall", "timely_recall", "burst_recall", "duty_cycle",
                                             "energy_per_min_mJ", "attack_success", "frr"]))
        L.append("")
    L.append("## Spam-intensity sweep (S2): mean over 30 realizations\n")
    sw = desc[desc.scenario == "spam"]
    for met in ("spam_success", "timely_recall", "track_recall", "frr", "duty_cycle", "energy_per_min_mJ",
                "mean_trigger_latency_ms"):
        p = sw[sw.metric == met].pivot(index="mode", columns="intensity", values="mean").reindex(MODES)
        L.append(f"**{met}**\n")
        L.append("| method | " + " | ".join(f"{c:g}x" for c in p.columns) + " |")
        L.append("|---|" + "---|" * len(p.columns))
        nd = 0 if met.startswith("energy") or met.endswith("_ms") else 3
        for md, row in p.iterrows():
            L.append(f"| {md} | " + " | ".join(f(v, nd) for v in row.values) + " |")
        L.append("")
    L.append("![spam sweep](test/fig_spam_sweep.png)\n![main](test/fig_main.png)\n")
    rv = os.path.join(TEST, "replay_variants.csv")
    if os.path.exists(rv):
        t = pd.read_csv(rv)
        L.append("## Replay detection per perturbation (S4, replay_exact + replay_perturbed test workloads)\n")
        L.append("| method | variant | replay frames | reached gate | blocked by gate | blocked as REPLAY | "
                 "gate detection rate | attack success (reached M7) |")
        L.append("|---|---|---|---|---|---|---|---|")
        for r in t.itertuples():
            L.append(f"| {r.mode} | {r.variant} {r.variant_name} | {r.replay_frames} | {r.gate_evaluated} | "
                     f"{r.gate_blocked} | {r.gate_blocked_as_replay} | {f(r.gate_detection_rate)} | "
                     f"{f(r.attack_success)} |")
        fr = pd.read_csv(os.path.join(TEST, "replay_scenarios_frr.csv"))
        for r in fr.itertuples():
            L.append(f"\n{r.mode}: legitimate requests at the gate {int(r.legit_evaluated)}, blocked "
                     f"{int(r.legit_blocked)} (FRR {f(r.frr)}), of which blocked as REPLAY "
                     f"{int(r.legit_blocked_as_replay)}.")
        L.append("")
    ab = os.path.join(TEST, "ablation_summary.csv")
    if os.path.exists(ab):
        a = pd.read_csv(ab)
        L.append("## Component ablations (S3, exploratory, test split, frozen parameters)\n")
        L.append("| method | ablation | condition | track recall | timely recall | duty | attack success | FRR |")
        L.append("|---|---|---|---|---|---|---|---|")
        for r in a.itertuples():
            L.append(f"| {r.mode} | {r.ablation} | {r.condition} | {f(r.track_recall)} | {f(r.timely_recall)} | "
                     f"{f(r.duty_cycle)} | {f(r.attack_success)} | {f(r.frr)} |")
        L.append("")
    # R1 vs R2 side by side (never pooled)
    if os.path.exists(R1):
        r1 = pd.read_csv(R1)
        L.append("## R1 synthetic study vs R2 real-detector-trace study (side by side, NOT pooled)\n")
        L.append("R1: synthetic detector distribution and parametric watcher features, 3600 s workloads, "
                 "10 seeds, archived on `claude/research-grade-simulation-r1m7cp`. R2: real frames, real "
                 "detector predictions, test split, 30 realizations. Recall definitions differ (R1 episode "
                 "recall vs R2 moving-track recall); the columns are not comparable across studies, only the "
                 "ordering of methods within each study is.\n")
        L.append("| scenario (R1 / R2) | method | R1 episode recall | R2 track recall | R1 duty | R2 duty | "
                 "R1 attack success | R2 attack success | R1 FRR | R2 FRR |")
        L.append("|---|---|---|---|---|---|---|---|---|---|")
        pairs = [("normal", "clean"), ("noisy", "noisy"), ("trigger_spam", "spam"), ("replay", "replay_perturbed"),
                 ("mixed", "mixed")]
        for s1, s2 in pairs:
            it = 1.0
            for md in ("always_on", "motion_only", "fixed_threshold", "event", "secure", "robust_event",
                       "robust_secure"):
                a = r1[(r1.scenario == s1) & (r1["mode"] == md)]

                def g1(c):
                    return a[c + "__mean"].iloc[0] if len(a) and c + "__mean" in a else float("nan")

                def g2(m):
                    x = desc[(desc.scenario == s2) & np.isclose(desc.intensity, it) & (desc["mode"] == md) &
                             (desc.metric == m)]
                    return x["mean"].iloc[0] if len(x) else float("nan")
                L.append(f"| {s1} / {s2} | {md} | {f(g1('episode_recall'))} | {f(g2('track_recall'))} | "
                         f"{f(g1('duty_cycle'))} | {f(g2('duty_cycle'))} | {f(g1('attack_success_rate'))} | "
                         f"{f(g2('attack_success'))} | {f(g1('false_rejection_rate'))} | {f(g2('frr'))} |")
        L.append("")
    L.append("## Frozen parameters\n")
    L.append("```json\n" + json.dumps({k: v for k, v in frozen.items() if not k.startswith("_")}, indent=1) +
             "\n```\n")
    with open(os.path.join(R2, "RESULTS_R2.md"), "w") as fh:
        fh.write("\n".join(L))
    print(f"wrote {os.path.join(R2, 'RESULTS_R2.md')} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
