#!/usr/bin/env python3
"""Import FUTURE Portenta H7 power/timing measurements and generate
config/power_model_calibrated.json (and an optional timing override JSON).

The simulation-assumption model config/power_model.json is NEVER modified.
Nothing in this repository has been measured yet; this script exists so the
measurements described in docs/HARDWARE_MINIMAL_R2.md / docs/R3_HARDWARE.md
can be dropped in without code changes.

Input CSV (one row per trial and state), columns:
  state      one of the power states of config/power_model.json
             (M4_IDLE, M4_MONITOR, M4_PROCESS, SECURITY_PROCESSING,
             RPC_COMMUNICATION, M7_SLEEP, M7_WAKEUP, M7_INFERENCE,
             M7_SECOND_PASS, M7_POSTPROCESS, M7_IDLE_AWAKE) or a timing key
             (timing:m7_wakeup_ms, timing:rpc_latency_ms, timing:inference_ms,
             timing:second_pass_cost_ms, timing:postprocess_base_ms,
             timing:m4_process_ms, timing:security_process_ms)
  voltage    supply voltage during the trial [V]   (power rows)
  current    mean current during the trial [mA]    (power rows)
  duration   window length [ms]                    (power rows: integration window; timing rows: the measured duration)
  trial      trial index
Optional columns: board_id, instrument, date, notes.

Power per trial = voltage * current [mW]; per state: mean, SD, 95 % t-CI over
trials. Timing per key: median (used) and IQR.

  python3 scripts/import_hardware_measurements.py measurements.csv \
      --out config/power_model_calibrated.json --timing-out config/timing_calibrated.json
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys

import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
STATES = ["M4_IDLE", "M4_MONITOR", "M4_PROCESS", "SECURITY_PROCESSING", "RPC_COMMUNICATION", "M7_SLEEP", "M7_WAKEUP",
          "M7_INFERENCE", "M7_SECOND_PASS", "M7_POSTPROCESS", "M7_IDLE_AWAKE"]
TIMING_KEYS = ["m7_wakeup_ms", "rpc_latency_ms", "inference_ms", "second_pass_cost_ms", "postprocess_base_ms",
               "m4_process_ms", "security_process_ms"]


def t975(n: int) -> float:
    from scipy import stats
    return float(stats.t.ppf(0.975, n - 1)) if n > 1 else float("nan")


def build(df: pd.DataFrame, base: dict) -> tuple[dict, dict]:
    need = {"state", "voltage", "current", "duration", "trial"}
    if not need.issubset(df.columns):
        raise SystemExit(f"missing columns: {sorted(need - set(df.columns))}")
    pw = df[~df.state.str.startswith("timing:")].copy()
    unknown = set(pw.state) - set(STATES)
    if unknown:
        raise SystemExit(f"unknown power states: {sorted(unknown)}")
    pw["power_mW"] = pw.voltage * pw.current
    model = {"units": "mW", "source": "measured", "calibrated": True,
             "_note": "Generated by scripts/import_hardware_measurements.py from physical measurements. "
                      "States without measurements keep the simulation assumption and are marked so.",
             "states": {}}
    for s in STATES:
        g = pw[pw.state == s].power_mW
        if len(g):
            sd = float(g.std(ddof=1)) if len(g) > 1 else float("nan")
            half = t975(len(g)) * sd / math.sqrt(len(g)) if len(g) > 1 else float("nan")
            model["states"][s] = {"power_mW": float(g.mean()), "sd_mW": sd, "ci95_mW": [float(g.mean() - half),
                                  float(g.mean() + half)], "n_trials": int(len(g)), "source": "measured",
                                  "core": base["states"][s]["core"], "description": base["states"][s]["description"]}
        else:
            st = dict(base["states"][s])
            st["source"] = "simulation_assumption (NOT measured)"
            model["states"][s] = st
    if any(v["source"] != "measured" for v in model["states"].values()):
        model["calibrated"] = False
        model["_note"] += " NOT fully calibrated: some states are still assumptions."
    timing = {}
    tm = df[df.state.str.startswith("timing:")]
    for k in TIMING_KEYS:
        g = tm[tm.state == f"timing:{k}"].duration
        if len(g):
            timing[k] = {"value": float(g.median()), "iqr": [float(g.quantile(0.25)), float(g.quantile(0.75))],
                         "n_trials": int(len(g)), "source": "measured"}
    meta = {c: sorted(df[c].dropna().astype(str).unique().tolist()) for c in ("board_id", "instrument", "date")
            if c in df.columns}
    model["measurement_meta"] = meta
    return model, timing


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("csv")
    ap.add_argument("--out", default=os.path.join(ROOT, "config", "power_model_calibrated.json"))
    ap.add_argument("--timing-out", default="")
    a = ap.parse_args()
    base_path = os.path.join(ROOT, "config", "power_model.json")
    if os.path.abspath(a.out) == os.path.abspath(base_path):
        raise SystemExit("refusing to overwrite the simulation-assumption model config/power_model.json")
    base = json.load(open(base_path))
    model, timing = build(pd.read_csv(a.csv), base)
    json.dump(model, open(a.out, "w"), indent=1)
    if a.timing_out:
        json.dump({k: v["value"] for k, v in timing.items()} | {"_measured": timing}, open(a.timing_out, "w"), indent=1)
    print(f"wrote {a.out} (calibrated={model['calibrated']}); timing keys: {sorted(timing)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
