#!/usr/bin/env python3
"""Generate RESULTS_SUMMARY.md from stored campaign CSVs.

Every number in the generated report is read from the aggregate CSV files of
the campaigns given on the command line; nothing is typed by hand.

Usage:
    python3 scripts/make_report.py --main <dir> [--ablation <dir>] [--sensitivity <dir>] [--smoke <dir>] --out FILE
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "eval_energy"))
from aggregate import ATTACK_SCENARIOS, MODE_ORDER, SCENARIO_ORDER  # noqa: E402


def pct(x, d=1):
    return "n/a" if x is None or (isinstance(x, float) and math.isnan(x)) else f"{100 * x:.{d}f}%"


def num(x, d=1):
    return "n/a" if x is None or (isinstance(x, float) and math.isnan(x)) else f"{x:.{d}f}"


def rel(path, base):
    return os.path.relpath(path, base)


def campaign_block(cdir: str, out_dir: str) -> list:
    meta = json.load(open(os.path.join(cdir, "config", "campaign.json")))
    val = pd.read_csv(os.path.join(cdir, "logs", "validation.csv"))
    wl = pd.read_csv(os.path.join(cdir, "logs", "workload_equality.csv"))
    errs = json.load(open(os.path.join(cdir, "logs", "errors.json")))
    return [f"* `{meta['campaign_id']}` ({meta.get('kind', '?')}): **{len(val)} runs executed**, "
            f"{int(val['validation_pass'].sum())} passed all structural validation checks, {len(errs)} run errors; "
            f"{len(wl)} shared workloads, all runs matched their workload hash: {bool(wl['all_runs_match'].all())}. "
            f"Git commit `{meta['git']['commit'][:12]}` (dirty={meta['git']['dirty']}), "
            f"simulated seconds per run: {meta.get('seconds')}. Directory: `{rel(cdir, out_dir)}`"]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--main", required=True)
    ap.add_argument("--ablation")
    ap.add_argument("--sensitivity")
    ap.add_argument("--smoke")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    out_dir = os.path.dirname(os.path.abspath(a.out))
    L = ["# Simulation results summary (auto-generated)", "",
         "Generated by `scripts/make_report.py` from stored campaign CSV files. All quantities are SIMULATED; "
         "energy is MODELED from uncalibrated simulation-assumption power states "
         "(`config/power_model.json`, `calibrated: false`). No value here is a physical measurement.", "",
         "## Campaigns", ""]
    for c in (a.smoke, a.main, a.ablation, a.sensitivity):
        if c:
            L += campaign_block(c, out_dir)
    L.append("")

    agg = os.path.join(a.main, "aggregate")
    sc = pd.read_csv(os.path.join(agg, "scenario_level.csv"))
    md = pd.read_csv(os.path.join(agg, "mode_level.csv"))
    runs = pd.read_csv(os.path.join(agg, "results_summary.csv"))
    pc = pd.read_csv(os.path.join(agg, "paired_comparisons.csv"))
    modes = [m for m in MODE_ORDER if m in set(md["mode"])]
    n_seeds = runs.groupby(["scenario", "mode"]).size().min()

    L += ["## Key observations (main campaign)", "",
          f"Matched design: {runs['scenario'].nunique()} scenarios x {len(modes)} modes x {n_seeds} seeds; every "
          "mode of a (scenario, seed) replayed the identical workload file.", ""]
    L += ["### Pooled over all scenarios (mean of per-run values)", "",
          "| mode | duty cycle | modeled energy/h (J) | saving vs always_on | episode recall | onset p95 (ms) | "
          "false alarms/h |", "|---|---|---|---|---|---|---|"]
    for m in modes:
        r = md[md["mode"] == m].iloc[0]
        L.append(f"| {m} | {pct(r['duty_cycle__mean'], 2)} | {num(r['energy_per_min_mJ__mean'] * 0.06)} | "
                 f"{pct(r['energy_saving_vs_always_on__mean'])} | {num(r['episode_recall__mean'], 3)} | "
                 f"{num(r['onset_latency_ms_p95__mean'])} | {num(r['false_alarms_per_hour__mean'], 2)} |")
    L.append("")

    # Energy composition for the event-driven modes.
    if "secure" in modes:
        r = md[md["mode"] == "secure"].iloc[0]
        share = r["energy_m4_mJ__mean"] / r["energy_total_mJ__mean"]
        L += [f"* In secure mode the always-on M4 accounts for {pct(share)} of modeled energy (pooled mean), so "
              "the modeled saving is dominated by the assumed M4 monitoring power, not by M7 duty cycle. "
              "See `aggregate/energy_model_sensitivity.csv` for how the saving changes when that assumption is "
              "scaled.", ""]

    att = [s for s in ATTACK_SCENARIOS if s in set(sc["scenario"])]
    if att:
        L += ["### Attack scenarios", "",
              "| scenario | mode | attack success rate | gate attack detection rate | FRR (real objects) | "
              "episode recall | modeled energy/h (J) |", "|---|---|---|---|---|---|---|"]
        for s in att:
            for m in [x for x in ("fixed_threshold", "event", "secure") if x in modes]:
                r = sc[(sc["scenario"] == s) & (sc["mode"] == m)].iloc[0]
                L.append(f"| {s} | {m} | {pct(r['attack_success_rate__mean'])} | "
                         f"{pct(r['attack_detection_rate__mean'])} | {pct(r['false_rejection_rate_object__mean'])} | "
                         f"{num(r['episode_recall__mean'], 3)} | {num(r['energy_per_min_mJ__mean'] * 0.06)} |")
        L.append("")

    L += ["### Per-scenario episode recall (object episodes detected at least once)", "",
          "| scenario | " + " | ".join(modes) + " |", "|---|" + "---|" * len(modes)]
    for s in [x for x in SCENARIO_ORDER if x in set(sc["scenario"])]:
        vals = [num(sc[(sc["scenario"] == s) & (sc["mode"] == m)]["episode_recall__mean"].iloc[0], 3) for m in modes]
        L.append(f"| {s} | " + " | ".join(vals) + " |")
    L.append("")

    if len(pc):
        sig = pc[pc["significant_holm_0.05"] == True]  # noqa: E712
        L += ["### Paired statistics", "",
              f"{len(pc)} paired Wilcoxon signed-rank comparisons (Holm-corrected over all of them); "
              f"{int(pc['p_value'].notna().sum())} had enough non-zero pairs to be tested; "
              f"{len(sig)} are significant at alpha = 0.05 after Holm correction. "
              "Full table: `aggregate/paired_comparisons.csv`.", ""]
        focus = pc[(pc["a"] == "secure") & (pc["b"] == "event") & pc["scenario"].isin(att)]
        if len(focus):
            L += ["| scenario | metric (secure - event) | median diff | rank-biserial | p (Holm) |", "|---|---|---|---|---|"]
            for _, r in focus.iterrows():
                p_txt = "n/a" if pd.isna(r["p_holm"]) else f"{r['p_holm']:.3g}"
                L.append(f"| {r['scenario']} | {r['metric']} | {r['median_diff']:.4g} | {r['rank_biserial']:.3f} | "
                         f"{p_txt} |")
            L.append("")

    if a.ablation:
        ab = pd.read_csv(os.path.join(a.ablation, "aggregate", "ablation.csv"))
        L += ["## Ablation (Table F)", "",
              "| scenario | variant | attack success rate | episode recall | FRR (real objects) | energy/h (J) |",
              "|---|---|---|---|---|---|"]
        for s in [x for x in SCENARIO_ORDER if x in set(ab["scenario"])]:
            for _, r in ab[ab["scenario"] == s].iterrows():
                L.append(f"| {s} | {r['label']} | {pct(r['attack_success_rate__mean'])} | "
                         f"{num(r['episode_recall__mean'], 3)} | {pct(r['false_rejection_rate_object__mean'])} | "
                         f"{num(r['energy_per_min_mJ__mean'] * 0.06)} |")
        L.append("")

    if a.sensitivity:
        se = pd.read_csv(os.path.join(a.sensitivity, "aggregate", "sensitivity.csv"))
        ai = se[se["sweep_param"] == "attack_intensity"]
        if len(ai):
            L += ["## Attack-intensity sensitivity", "",
                  "| scenario | intensity | mode | attack success rate | episode recall | energy/h (J) |",
                  "|---|---|---|---|---|---|"]
            for _, r in ai.sort_values(["scenario", "sweep_value", "mode"]).iterrows():
                L.append(f"| {r['scenario']} | {r['sweep_value']:g} | {r['mode']} | "
                         f"{pct(r['attack_success_rate__mean'])} | {num(r['episode_recall__mean'], 3)} | "
                         f"{num(r['energy_per_min_mJ__mean'] * 0.06)} |")
            L.append("")
        L += [f"Other sweeps: `{rel(os.path.join(a.sensitivity, 'aggregate', 'tables', 'table_G_sensitivity.md'), out_dir)}`.", ""]

    L += ["## Tables and figures", ""]
    for c in (a.main, a.ablation, a.sensitivity):
        if not c:
            continue
        tdir = os.path.join(c, "aggregate", "tables")
        for f in sorted(os.listdir(tdir)) if os.path.isdir(tdir) else []:
            if f.endswith(".md"):
                L.append(f"* `{rel(os.path.join(tdir, f), out_dir)}`")
        fdir = os.path.join(c, "figures")
        for f in sorted(os.listdir(fdir)) if os.path.isdir(fdir) else []:
            if f.endswith(".png"):
                L.append(f"* `{rel(os.path.join(fdir, f), out_dir)}`")
    with open(a.out, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
